#Importación de la imagen base con python
FROM python:3.12-slim

# Creamos carpeta de trabajo del contenedor 
WORKDIR /app

#Copiamos los requerimientos del servidor 
COPY requirements.txt . 

#Instalar Requerimientos 
RUN pip install --no-cache-dir -r requirements.txt

#Copiar API
COPY ./app ./app

#exponer puerto
EXPOSE 5000


#Comando de ejecución FASTAPI
CMD ["uvicorn", "app.main:app","--host", "0.0.0.0", "--port","5000", "--reload"]
